version: '3.9'
services:
  redis:
    image: redis:alpine
    container_name: backing-redis
  redis_proxy:
    image: redis_proxy:latest
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    environment:
      - PROXY_IP=${PROXY_IP}
      - PROXY_PORT=${PROXY_PORT}
    depends_on:
      - redis
    container_name: redis-proxy
